services:
  db:
    image: postgres:16
    container_name: blankapp_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: blankapp_metabase
    depends_on:
      db:
        condition: service_healthy
    environment:
      # For small setups, keep default H2 internal DB for Metabase app metadata.
      MB_JETTY_PORT: 3000
      JAVA_OPTS: "-Xms256m -Xmx768m"
    ports:
      - "3000:3000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blankapp_streamlit
    depends_on:
      db:
        condition: service_healthy
    environment:
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"

  loader:
    build:
      context: ./loader
      dockerfile: Dockerfile
    container_name: blankapp_loader
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppassword
      # Indicators and countries are configurable via envs if needed
      WB_INDICATORS: "LO.PISA.MAT,LO.PISA.REA,LO.PISA.SCI"
      WB_COUNTRIES: "KOR,JPN,USA,DEU,FRA,CHN,GBR,FIN,SGP,CAN,AUS"
    restart: "on-failure"

volumes:
  db_data:
